app/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url('', include('auth.urls')),
        url('calculimc/', include('calculimc.urls')),
        url('calculdej/', include('calculdej.urls')),
        url('consulterdossier/', include('consulterdossier.urls')),
        url('consultertouslesdossiers/', include('consultertouslesdossiers.urls')),
        url(r'^captcha/', include('captcha.urls')),
]

app/calculdej/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.calculdej, name='calculdej'),
    path('calculdejmb', views.calculdejmb, name='calculdejmb'),
    path('calculdejprofessionnelle', views.calculdejprofessionnelle, name='calculdejprofessionnelle'),
    path('calculdejusuelle', views.calculdejusuelle, name='calculdejusuelle'),
    path('calculdejloisir', views.calculdejloisir, name='calculdejloisir'),
    path('calculdejsport', views.calculdejsport, name='calculdejsport'),
    path('calculdejresultat', views.calculdejresultat, name='calculdejresultat'),
    path('load_act/', views.load_act, name='load_act'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    path('alertmsg/', views.alertmsg, name='alertmsg'),
]

app/calculdej/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone


class Categorie(models.Model):
    nom = models.CharField(max_length=30)

    # nous avons 4 types : professionnelle, usuelle, loisir, sportive
    CATEGORIE_CHOICES = (
        ('Professionnelles', 'Professionnelles'),
        ('Usuelles', 'Usuelles'),
        ('Loisirs', 'Loisirs'),
        ('Sportives', 'Sportives'),
    )
    typeCat = models.CharField(
        max_length=16,
        choices=CATEGORIE_CHOICES,
    )


    def __str__(self):
        return self.nom

class Activite(models.Model):
    coef = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    titre = models.CharField(max_length=100)
    categorie = models.ForeignKey('Categorie', on_delete=models.CASCADE)

    def __str__(self):
        return self.titre

class Dossier(models.Model):
    #titre = models.CharField(max_length=30,default="")
    date = models.DateTimeField(default=timezone.now, blank=True, verbose_name="Date création")
    auteur = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    taille = models.DecimalField(default=0.0,max_digits=5, decimal_places=2)
    poids = models.DecimalField(default=0.0,max_digits=5, decimal_places=2)
    pathologie = models.CharField(default="",max_length=20)
    age = models.IntegerField(default=0)
    de = models.DecimalField(default=0.00,max_digits=5, decimal_places=2)
    sexe = models.CharField(default="",max_length=1)
    det=models.DecimalField(default=0.00,max_digits=10, decimal_places=2)
    imc=models.DecimalField(default=0.00,max_digits=10, decimal_places=2)
    mb=models.DecimalField(default=0.00,max_digits=10, decimal_places=2)
    niveau=models.CharField(default="",max_length=20)
    dernier = models.BooleanField(default=True)

    def modif(self):
        self.dernier=False

class Travail(models.Model):
    dossierTrav = models.ForeignKey('Dossier', on_delete=models.CASCADE)
    categorieTrav = models.ForeignKey('Categorie', on_delete=models.CASCADE)
    activiteTrav = models.ForeignKey('Activite', on_delete=models.CASCADE)
    dureeTrav = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    coefTrav = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)

app/calculdej/forms.py
from django import forms
from calculdej.models import Categorie, Activite, Dossier, Travail
from django.forms import formset_factory
from django.contrib.auth.models import User

class CalculDejForm(forms.Form):
    cat = forms.ModelChoiceField(label="Catégorie", queryset=Categorie.objects.all())
    act = forms.ModelChoiceField(label="Activité", queryset=None)
    duree = forms.DecimalField(label="Durée (h)", decimal_places=2,min_value=0)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['act'].queryset = Activite.objects.none()

        if 'cat' in self.data:
            try:
                cat_t = Categorie(self.data.get('cat'))
                self.fields['act'].queryset = Activite.objects.filter(categorie=cat_t)
            except (ValueError, TypeError):
                pass
        else:
            self.fields['act'].queryset = Activite.objects.none()

    def CatProfessionnelles(self):
        lc = Categorie.objects.filter(typeCat='Professionnelles')
        c = lc.reverse()[0]
        la = Activite.objects.filter(categorie=c)
        self.fields['cat'].queryset = lc
        self.fields['cat'].empty_label = None
        self.fields['act'].queryset = la



    def CatUsuelles(self):
        lc = Categorie.objects.filter(typeCat='Usuelles')
        c = lc.reverse()[0]
        la = Activite.objects.filter(categorie=c)
        self.fields['cat'].queryset = lc
        self.fields['cat'].empty_label = None
        self.fields['act'].queryset = la

    def CatLoisirs(self):
        l = Categorie.objects.filter(typeCat='Loisirs')
        self.fields['cat'].queryset = l

    def CatSportives(self):
        l = Categorie.objects.filter(typeCat='Sportives')
        self.fields['cat'].queryset = l

class CalculMBForm(forms.Form):
    CHOICES=[('M','M'),
             ('F','F'),
                 ]
    sexe = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)
    poids = forms.DecimalField(label='Poids (en kg)',decimal_places=2,min_value=0.0)
    taille = forms.DecimalField(label='Taille (en cm)',decimal_places=2,min_value=0.0)
    age = forms.IntegerField(min_value=0)
    pathologie = forms.CharField(label='Pathologie ?',required=False)


class DeplacementForm(forms.Form):
    dureelentsansport = forms.DecimalField(initial=0, label="Lent sans port de charge",decimal_places=2,min_value=0)
    dureemoderesansport = forms.DecimalField(initial=0, label="Modéré sans port de charge",decimal_places=2,min_value=0)
    dureemodereavecport = forms.DecimalField(initial=0, label="Modéré avec port de charge",decimal_places=2,min_value=0)
    dureeintense = forms.DecimalField(initial=0, label="Intense",decimal_places=2,min_value=0)

    def initialval(self):
        self.fields['dureelentsansport'] = 0
        self.fields['dureemoderesansport'] = 0
        self.fields['dureemodereavecport'] = 0
        self.fields['dureeintense'] = 0

app/calculdej/views.py
from .forms import CalculDejForm, DeplacementForm, CalculMBForm
# from .forms import CalculDejForm, SupprimerForm, CalculImcForm, ValideForm
from calculdej.models import Categorie
from calculdej.models import Activite
from calculdej.models import Dossier
from calculdej.models import Travail
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from decimal import Decimal
from weasyprint import HTML, CSS
from django.conf import settings
import os
from django.template.loader import render_to_string

poids = 0
taille = 0
sexe = "M"
age = 0
pathologie = ""

deplacements = []

@login_required
def calculdej(request):
    return render(request, 'calculdej/calculdej.html')

@login_required
def calculdejmb(request):
    global poids
    global taille
    global sexe
    global age
    global pathologie

    quitter1 = False
    if request.method == 'GET':
        a = request.GET.get('calculdejprofessionnelle')
        b = request.GET.get('calculdejusuelle')
        c = request.GET.get('calculdejloisir')
        d = request.GET.get('calculdejsport')
        if a is None:
            quitter1 = True
        if b is None:
            quitter1 = True
        if c is None:
            quitter1 = True
        if d is None:
            quitter1 = True

    formImc = CalculMBForm(request.POST or None)
    if request.method == 'POST' and 'btnsuivantt' in request.POST:
        if formImc.is_valid():
            poids = formImc.cleaned_data['poids']
            taille = formImc.cleaned_data['taille']
            sexe = formImc.cleaned_data['sexe']
            age = formImc.cleaned_data['age']
            pathologie = formImc.cleaned_data['pathologie']
            return redirect(reverse(calculdejprofessionnelle))

    return render(request, 'calculdej/calculdejmb.html', locals())


@login_required
def alertmsg(request):
    return render(request, 'calculdej/alertmsg.html', locals())

def calculDureeTotale( travails ):
    # Calcul Durée Totale
    duree = 0
    for tmp in travails:
        test = False
        for cat in Categorie.objects.filter(typeCat="Sportives"):
            if tmp.categorieTrav == cat:
                test = True
        for cat in Categorie.objects.filter(typeCat="Loisirs"):
            if tmp.categorieTrav == cat:
                test = True
        if test:
            duree += tmp.dureeTrav/7
        else:
            duree += tmp.dureeTrav

    return round(duree, 2)

@login_required
def calculdejprofessionnelle(request):
    global deplacements

    formDej = CalculDejForm(request.POST or None)
    formDeplacement = DeplacementForm(request.POST or None)
    formDej.CatProfessionnelles()
    cat = None
    dossier = Dossier.objects.filter(dernier=True)
    if dossier:
        dossier = dossier.reverse()[0]
    else:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)
    if dossier.dernier != True:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)

    if request.method == 'POST' and 'btnsuivant' in request.POST:
        if formDej.is_valid() and formDeplacement.is_valid():
            cat = formDej.cleaned_data['cat']
            act = formDej.cleaned_data['act']
            duree = formDej.cleaned_data['duree']
            coef_act = act.coef
            dp = duree * coef_act
            Travail.objects.create(dossierTrav=dossier,categorieTrav=cat,activiteTrav=act,dureeTrav=duree,coefTrav=coef_act)
            # envoi = True
            if 'rdouinon' in request.POST:
                valrd = str(request.POST.get('rdouinon'))
                if valrd == "Oui":
                    deplacements.append(float(formDeplacement.cleaned_data['dureelentsansport']))
                    deplacements.append(float(formDeplacement.cleaned_data['dureemoderesansport']))
                    deplacements.append(float(formDeplacement.cleaned_data['dureemodereavecport']))
                    deplacements.append(float(formDeplacement.cleaned_data['dureeintense']))
                elif valrd == "Non":
                    deplacements = [0,0,0,0]

            return redirect(reverse(calculdejusuelle))

    travails = Travail.objects.filter(dossierTrav=dossier).filter(categorieTrav__typeCat__contains='Professionnelles')

    return render(request, 'calculdej/calcdejprofessionnelle.html', locals())


@login_required
def calculdejusuelle(request):

    quitter = False
    if request.method == 'GET' and (not ('btnsuivant' in request.GET)):
        quitter = True

    formDej = CalculDejForm(request.POST or None)
    formDej.CatUsuelles()
    cat = None
    dossier = Dossier.objects.filter(dernier=True)
    if dossier:
        dossier = dossier.reverse()[0]
    else:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)
    if dossier.dernier != True:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)

    if request.method == 'POST' and 'btnajouter' in request.POST:
        if formDej.is_valid():
            cat = formDej.cleaned_data['cat']
            act = formDej.cleaned_data['act']
            duree = formDej.cleaned_data['duree']
            coef_act = act.coef
            dp = duree * coef_act
            Travail.objects.create(dossierTrav=dossier,categorieTrav=cat,activiteTrav=act,dureeTrav=duree,coefTrav=coef_act)
            envoi = True

    elif request.method == 'POST' and 'btnsupprimer' in request.POST:
        id_supp = int(request.POST.get('btnsupprimer'))
        Travail.objects.get(id=id_supp).delete()
        return HttpResponseRedirect(request.path_info)

    travails = Travail.objects.filter(dossierTrav=dossier).filter(categorieTrav__typeCat__contains='Usuelles')
    travails_all = Travail.objects.filter(dossierTrav=dossier)
    duree_tot = calculDureeTotale( travails_all )
    duree_depassee = duree_tot > 24

    return render(request, 'calculdej/calcdejusuelle.html', locals())

@login_required
def calculdejloisir(request):
    formDej = CalculDejForm(request.POST or None)
    formDej.CatLoisirs()
    dossier = Dossier.objects.filter(dernier=True)
    cat = None
    if dossier:
        dossier = dossier.reverse()[0]
    else:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)
    if dossier.dernier != True:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)

    if request.method == 'POST' and 'btnajouter' in request.POST:
        if formDej.is_valid():
            cat = formDej.cleaned_data['cat']
            act = formDej.cleaned_data['act']
            duree = formDej.cleaned_data['duree']
            coef_act = act.coef
            dp = duree * coef_act
            Travail.objects.create(dossierTrav=dossier,categorieTrav=cat,activiteTrav=act,dureeTrav=duree,coefTrav=coef_act)
            envoi = True

    elif request.method == 'POST' and 'btnsupprimer' in request.POST:
        id_supp = int(request.POST.get('btnsupprimer'))
        Travail.objects.get(id=id_supp).delete()
        return HttpResponseRedirect(request.path_info)

    travails = Travail.objects.filter(dossierTrav=dossier).filter(categorieTrav__typeCat__contains='Loisirs')
    travails_all = Travail.objects.filter(dossierTrav=dossier)
    duree_tot = calculDureeTotale( travails_all )
    duree_depassee = duree_tot > 24

    return render(request, 'calculdej/calcdejloisir.html', locals())

@login_required
def calculdejsport(request):
    formDej = CalculDejForm(request.POST or None)
    formDej.CatSportives()
    cat = None
    dossier = Dossier.objects.filter(dernier=True)
    if dossier:
        dossier = dossier.reverse()[0]
    else:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)
    if dossier.dernier != True:
        dossier = Dossier.objects.create(auteur=request.user,dernier=True)

    if request.method == 'POST' and 'btnajouter' in request.POST:
        if formDej.is_valid():
            cat = formDej.cleaned_data['cat']
            act = formDej.cleaned_data['act']
            duree = formDej.cleaned_data['duree']
            coef_act = act.coef
            dp = duree * coef_act
            Travail.objects.create(dossierTrav=dossier,categorieTrav=cat,activiteTrav=act,dureeTrav=duree,coefTrav=coef_act)
            envoi = True
    elif request.method == 'POST' and 'btnterminer' in request.POST:
        # dossier.dernier=False
        # dossier.save()
        # return render(request, 'calculdej/calculdejresultat.html', locals())
        return calculdejresultat(request)

    elif request.method == 'POST' and 'btnsupprimer' in request.POST:
        id_supp = int(request.POST.get('btnsupprimer'))
        Travail.objects.get(id=id_supp).delete()
        return HttpResponseRedirect(request.path_info)

    travails = Travail.objects.filter(dossierTrav=dossier).filter(categorieTrav__typeCat__contains='Sportives')

    travails_all = Travail.objects.filter(dossierTrav=dossier)
    duree_tot = calculDureeTotale( travails_all )
    duree_depassee = duree_tot > 24

    return render(request, 'calculdej/calcdejsport.html', locals())

# Calcul d'une DE en fonction d'une Catégorie et de sa liste d'Activités
def calculDE( cat, activites, MB, TD ):
    global deplacements

    dureeNap = 0
    sommeNap = 0
    for tmp in activites:
        if cat == "Professionnelles":
            dureeNap += tmp.dureeTrav
            sommeNap += (tmp.dureeTrav-Decimal(sum(deplacements))) * tmp.activiteTrav.coef
        if cat == "Loisirs" or cat == "Sportives":
            dureeNap += tmp.dureeTrav/7
            sommeNap += tmp.dureeTrav/7 * tmp.activiteTrav.coef
        if cat == "Usuelles":
            dureeNap += tmp.dureeTrav
            sommeNap += tmp.dureeTrav * tmp.activiteTrav.coef

    if dureeNap == 0:
        return 0
    else:
        if cat == "Professionnelles":

app/calculdej/templates/calculdej/acts.html
<option value="">---------</option>
{% for act in acts %}
<option value="{{ act.pk }}"> {{ act }} : {{ act.coef }} </option>
{% endfor %}

app/calculdej/templates/calculdej/alertmsg.html
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
		<script>

		$(window).on("beforeunload", function() {
			return "Are you sure? You didn't finish the form!";
		});

		$(document).ready(function() {
			$("#myForm").on("submit", function(e) {
				//check form to make sure it is kosher
				//remove the ev
				$(window).off("beforeunload");
				return true;
			});
		});
		</script>

app/calculdej/templates/calculdej/calcdejloisir.html
{% extends "baseActivite.html" %}

{% load crispy_forms_tags %}
{% block css %}
body{
  background-image: url("/static/img/loisir.jpg");
  background-size: cover;
}
{% endblock %}
{% block title %}DEJAppli - Ma DEJ{% endblock %}
{% block header %}<h1>Activités Loisirs</h1>{% endblock %}

{% block explication %}

<h4>Ajoutez toutes les activités loisirs que vous faites en heure par semaine.</h4>

{% endblock %}

{% block form %}

<form id="calcForm" method="post"
 data-act-url="{% url 'load_act' %}">
    {% csrf_token %}
  {{ formDej|crispy }}
    <button class="btn btn-success" type="submit" name="btnajouter">Ajouter</button>
</form>

<div>
</br>
</br>
  {%if duree_depassee %}
    <h2 class="row" style="color:red;">durée totale (h) : {{duree_tot }}</h2>
    <p class="row" style="color:red;font-size:20px"> Attention vous ne devez pas dépasser 24 heures, vous devez supprimer certaines activités </p>
  {%else%}
    <h2 class="row" style="color:green;">durée totale (h) : {{duree_tot }}</h2>
  {%endif%}

</div>

{% endblock %}

{% block tab %}

<table class="table">
  <thead>
       <tr>
           <th>Categorie</th>
           <th>Activite</th>
           <th>Duree</th>
       </tr>
   </thead>
   <tbody>
       {% for trav in travails %}
       <tr>
           <td>{{ trav.categorieTrav }} </td>
           <td>{{ trav.activiteTrav }} </td>
           <td>{{ trav.dureeTrav }} </td>
           <td>
             <form method="post">
                 {% csrf_token %}
                 <button class="btn btn-danger btn-xs" type="submit" name="btnsupprimer" value="{{trav.id}}">Supprimer</button>
             </form>
            </td>
       </tr>
       <tr>
      {%endfor%}
</table>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_cat").change(function () {
      var url = $("#calcForm").attr("data-act-url");  // get the url of the `load_cities` view
      var cat_select = $(this).val();  // get the selected country ID from the HTML input
      // alert(cat_sls$elect);
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'cat': cat_select       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          // acts = activites.filter(categorie=cat)
          $("#id_act").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
</script>

{% endblock %}

{% block footer %}

<a class="btn btn-default" href="{% url 'calculdejsport' %}" role="button">Suivant</a>

{% endblock %}

app/calculdej/templates/calculdej/calcdejprofessionnelle.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block css %}
body{
  background-image: url("/static/img/work.jpg");
  background-size: cover;
}
{% endblock %}
{% block title %}DEJAppli - Ma DEJ{% endblock %}
{% block header %}<h1>Activités Professionnelles</h1>{% endblock %}

{% block content %}


<!-- {{ formDej|crispy }} -->
<!-- {{ formDeplacement|crispy }} -->

<div class="row">
  <h4>Sélectionnez votre métier ainsi que le temps par jour que vous y passez.</h4>
</div>

<div class="row">

<form id="calcForm" method="post"
 data-act-url="{% url 'load_act' %}" class="form-inline">
<div class="row">
  {% csrf_token %}
  <div class="row form-group has-feedback">
    <div style="display: none">
      {{ formDej.cat|as_crispy_field }}
    </div>
    {{ formDej.act|as_crispy_field }}
    {{ formDej.duree|as_crispy_field }}
  </div>
</div>

<div class="row info-form">
  <p>Vous deplacez-vous au travail ?
  <br>
  <input type="radio" id="btn1" name="rdouinon" onclick="myFunctionOui()" value="Oui"/> Oui
  <input type="radio" id="btn1" name="rdouinon" checked="checked" onclick="myFunctionNon()" value="Non"/> Non
  </p>
</div>

<div id="myDIV" style="display: none" class="row">
  <p>Veuillez indiquer le temps correspondant en heure pour chaque type de déplacement</p>
  <div class="row">
    <div class="col-sm-6">
      {{ formDeplacement.dureelentsansport|as_crispy_field }}
    </div>
    <div class="col-sm-6">
      {{ formDeplacement.dureemoderesansport|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      {{ formDeplacement.dureemodereavecport|as_crispy_field }}
    </div>
    <div class="col-sm-6">
      {{ formDeplacement.dureeintense|as_crispy_field }}
    </div>
  </div>
</div>

</div>


<div class="row">
  <input id="btnSuivant" class="btn btn-default" type="submit" name="btnsuivant" value="Suivant">
</div>

</form>

<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container-fluid">
      <ul class="nav navbar-nav navbar-center">
        <li class="nav-item"><a href="/calculdej/calculdejprofessionnelle">Activités Professionnelles</a></li>
        <li class="nav-item"><a href="/calculdej/calculdejusuelle">Activités Usuelles</a></li>
        <li class="nav-item"><a href="/calculdej/calculdejloisir">Activités Loisirs</a></li>
        <li class="nav-item"><a href="/calculdej/calculdejsport">Activités Sportives</a></li>
      </ul>
  </div>
</nav>

<script type="text/javascript">
  $(document).ready(function () {
      var url = window.location;
      $('ul.nav a[href="'+ url +'"]').parent().addClass('active');
      $('ul.nav a').filter(function() {
           return this.href == url;
      }).parent().addClass('active');
  });
</script>


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_cat").change(function () {
    var url = $("#calcForm").attr("data-act-url");  // get the url of the `load_cities` view
    var cat_select = $(this).val();  // get the selected country ID from the HTML input
    // alert(cat_sls$elect);
    $.ajax({                       // initialize an AJAX request
      url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
      data: {
        'cat': cat_select       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
        // acts = activites.filter(categorie=cat)
        $("#id_act").html(data);  // replace the contents of the city input with the data that came from the server
      }
    });

  });
</script>

<script type="text/javascript">
function myFunctionNon() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "block") {
    x.style.display = "none";
  }
}

function myFunctionOui() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  }

}
</script>


<!-- <a class="btn btn-default" href="{% url 'calculdejusuelle' %}" role="button" name="asuivant">Suivant</a> -->
<!-- <form method="post">
  {% csrf_token %}
  <input id="btnSuivant" class="btn btn-default" type="submit" name="btnsuivant" value="Suivant">
</form> -->
{% endblock %}

app/calculdej/templates/calculdej/calcdejsport.html
{% extends "baseActivite.html" %}

{% load crispy_forms_tags %}
{% block css %}
body{
  background-image: url("/static/img/sport.jpg");
  background-size: cover;
}
{% endblock %}
{% block title %}DEJAppli - Ma DEJ{% endblock %}
{% block header %}<h1>Activités Sportives</h1>{% endblock %}

{% block explication %}

<h4>Ajoutez toutes les activités sportives que vous faites en heure par semaine.</h4>

{% endblock %}

{% block form %}

<form id="calcForm" method="post"
 data-act-url="{% url 'load_act' %}">
    {% csrf_token %}
    {{ formDej|crispy }}
    <button class="btn btn-success" type="submit" name="btnajouter">Ajouter</button>
</form>


<div>
</br>
</br>
  {%if duree_depassee %}
    <h2 class="row" style="color:red;">durée totale (h) : {{duree_tot }}</h2>
    <p class="row" style="color:red;font-size:20px"> Attention vous ne devez pas dépasser 24 heures, vous devez supprimer certaines activités </p>
  {%else%}
    <h2 class="row" style="color:green;">durée totale (h) : {{duree_tot }}</h2>
  {%endif%}

</div>
{% endblock %}

{% block tab %}

<table class="table">
  <thead>
       <tr>
           <th>Categorie</th>
           <th>Activite</th>
           <th>Duree</th>
       </tr>
   </thead>
   <tbody>
       {% for trav in travails %}
       <tr>
           <td>{{ trav.categorieTrav }} </td>
           <td>{{ trav.activiteTrav }} </td>
           <td>{{ trav.dureeTrav }} </td>
           <td>
             <form method="post">
                 {% csrf_token %}
                 <button class="btn btn-danger btn-xs" type="submit" name="btnsupprimer" value="{{trav.id}}">Supprimer</button>
             </form>
            </td>
       </tr>
       <tr>
      {%endfor%}
</table>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_cat").change(function () {
      var url = $("#calcForm").attr("data-act-url");  // get the url of the `load_cities` view
      var cat_select = $(this).val();  // get the selected country ID from the HTML input
      // alert(cat_sls$elect);
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'cat': cat_select       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          // acts = activites.filter(categorie=cat)
          $("#id_act").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
</script>

{% endblock %}

{% block footer %}

<form method="post">
  {% csrf_token %}
  <a class="btn btn-default" href="{% url 'calculdejresultat' %}" role="button">Terminer</a>
</form>

{% endblock %}

app/calculdej/templates/calculdej/calculdej.html
{% extends "base.html" %}

{% block header %}<h1>Ma Dépense Energétique Journalière</h1>{% endblock %}

{% block content %}

<div class="row">
  <h4>Vous allez ici répondre à une série de question et remplir une liste d'activités types d'une journée et d'une semaine.<br>A partir de tout cela vous connaîtrez votre niveau d'activité journalière.</h4>
</div>

<a class="btn btn-default" href="{% url 'calculdejmb' %}" role="button">Commencer</a>

{% endblock %}

app/calculdej/templates/calculdej/pdf.html
{% extends "base.html" %}